# Generated by Django 6.0.2 on 2026-02-27 02:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inscripciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Área de Interés',
                'verbose_name_plural': 'Áreas de Interés',
            },
        ),
        migrations.CreateModel(
            name='FormularioDeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('profesionOcupacion', models.CharField(max_length=30)),
                ('servicioElegido', models.CharField(choices=[('Voluntariado de Base', 'Voluntariado de Base'), ('Candidato a salir al campo', 'Candidato a salir al campo'), ('Intercesion', 'Intercesion'), ('Futuros tutores de HUT', 'Futuros tutores de HUT'), ('Movilizador', 'Movilizador')], max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Formulario de Decisión',
                'verbose_name_plural': 'Formularios de Decisión',
            },
        ),
        migrations.CreateModel(
            name='OpcionesMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=50, unique=True)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Icono', models.CharField(max_length=100)),
                ('TipoOpcion', models.IntegerField(choices=[(1, 'Reportes'), (2, 'Formulario'), (3, 'Gráficos')])),
                ('ruta', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Opción de Menú',
                'verbose_name_plural': 'Opciones de Menú',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paisNombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['paisNombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.IntegerField(choices=[(1001, 'Super'), (2002, 'Directivo'), (3003, 'Coordinador'), (111111, 'Desautorizado')])),
                ('reset_token', models.CharField(blank=True, max_length=100, null=True)),
                ('ultimoIngreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='ProvinciaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinciaNombre', models.CharField(max_length=100)),
                ('idPais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.pais')),
            ],
            options={
                'verbose_name': 'Provincia/Estado',
                'verbose_name_plural': 'Provincias/Estados',
            },
        ),
        migrations.CreateModel(
            name='FormularioInscripcionHUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=25)),
                ('edad', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(13)])),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('congregacion', models.CharField(max_length=50)),
                ('pastor', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('estadoCivil', models.CharField(choices=[('Soltera/o', 'Soltera/o'), ('Casada/o', 'Casada/o')], max_length=9, verbose_name='Estado Civil')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('abandonado', models.BooleanField(default=False)),
                ('fecha_abandono', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.pais')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.provinciaestado')),
            ],
            options={
                'verbose_name': 'Inscripción HUT',
                'verbose_name_plural': 'Inscripciones HUT',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('pais_origen', models.CharField(max_length=100)),
                ('pais_residencia', models.CharField(max_length=100)),
                ('provincia_residencia', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('miembro_iglesia', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=10)),
                ('cual_iglesia', models.CharField(blank=True, max_length=255)),
                ('sirve_en_iglesia', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=10)),
                ('cual_servicio', models.CharField(blank=True, max_length=255)),
                ('tiempo_asistiendo', models.CharField(blank=True, max_length=100)),
                ('voluntario_otra_org', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=10)),
                ('cual_org', models.CharField(blank=True, max_length=255)),
                ('hizo_hut', models.CharField(choices=[('SI', 'Sí'), ('TODAVIA_NO', 'Todavía no')], max_length=20)),
                ('hizo_reacciona', models.CharField(choices=[('SI', 'Sí'), ('TODAVIA_NO', 'Todavía no')], max_length=20)),
                ('deseo_salir_campo', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NO_POR_AHORA', 'No por ahora'), ('CORTO_PLAZO', 'Por corto plazo')], max_length=30)),
                ('nivel_estudio', models.CharField(choices=[('PRIMARIA_COMPLETA', 'Primaria completa'), ('SECUNDARIA_INCOMPLETA', 'Secundaria incompleta'), ('SECUNDARIA_COMPLETA', 'Secundaria completa'), ('TERCIARIO_INCOMPLETO', 'Terciario incompleto'), ('TERCIARIO_COMPLETO', 'Terciario completo'), ('UNIVERSITARIO_INCOMPLETO', 'Universitario incompleto'), ('UNIVERSITARIO_COMPLETO', 'Universitario completo')], max_length=30)),
                ('cursos_formacion', models.TextField(blank=True)),
                ('experiencia_profesional', models.TextField(blank=True)),
                ('foto_rostro', models.ImageField(upload_to='fotos_rostro/', validators=[inscripciones.models.validar_extension_imagen])),
                ('areas_interes', models.ManyToManyField(blank=True, to='inscripciones.areainteres')),
            ],
            options={
                'verbose_name': 'Voluntario',
                'verbose_name_plural': 'Voluntarios',
            },
        ),
    ]
