# Generated by Django 4.2.28 on 2026-05-21 23:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inscripciones.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Área de Interés',
                'verbose_name_plural': 'Áreas de Interés',
            },
        ),
        migrations.CreateModel(
            name='CursoHUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Curso')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('activo', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('inscripciones_abiertas', models.BooleanField(default=False, verbose_name='Inscripciones Abiertas')),
            ],
            options={
                'verbose_name': 'Curso HUT',
                'verbose_name_plural': 'Cursos HUT',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='FormularioDeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('profesionOcupacion', models.CharField(max_length=30)),
                ('servicioElegido', models.CharField(choices=[('Voluntariado de Base', 'Voluntariado de Base'), ('Candidato a salir al campo', 'Candidato a salir al campo'), ('Intercesion', 'Intercesion'), ('Futuros tutores de HUT', 'Futuros tutores de HUT'), ('Movilizador', 'Movilizador')], max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Formulario de Decisión',
                'verbose_name_plural': 'Formularios de Decisión',
            },
        ),
        migrations.CreateModel(
            name='OpcionesMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=50, unique=True)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Icono', models.CharField(max_length=100)),
                ('TipoOpcion', models.IntegerField(choices=[(1, 'Reportes'), (2, 'Formulario'), (3, 'Gráficos')])),
                ('ruta', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Opción de Menú',
                'verbose_name_plural': 'Opciones de Menú',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paisNombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['paisNombre'],
            },
        ),
        migrations.CreateModel(
            name='TerminosCondiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CANDIDATO', 'Candidato'), ('VOLUNTARIO', 'Voluntario'), ('INTERESADO', 'Interesado')], max_length=30, unique=True)),
                ('texto_html', models.TextField(help_text='Texto HTML para los términos y condiciones de este rol.')),
            ],
            options={
                'verbose_name': 'Términos y Condiciones',
                'verbose_name_plural': 'Términos y Condiciones',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.IntegerField(choices=[(1001, 'Super'), (2002, 'Directivo'), (3003, 'Coordinador'), (111111, 'Desautorizado')])),
                ('reset_token', models.CharField(blank=True, max_length=100, null=True)),
                ('ultimoIngreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('pais_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('pais_residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia_residencia', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('hijos', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=10)),
                ('fechas_nacimiento_hijos', models.TextField(blank=True, help_text='Ej: Juan (12-05-2015)')),
                ('con_quien_convive', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_pastor', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_pastor', models.CharField(blank=True, max_length=100, null=True)),
                ('rol_agencia', models.CharField(blank=True, choices=[('CANDIDATO', 'Candidato'), ('VOLUNTARIO', 'Voluntario'), ('INTERESADO', 'Interesado')], max_length=30, null=True)),
                ('miembro_iglesia', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=10, null=True)),
                ('cual_iglesia', models.CharField(blank=True, max_length=255)),
                ('sirve_en_iglesia', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=10, null=True)),
                ('cual_servicio', models.CharField(blank=True, max_length=255)),
                ('tiempo_asistiendo', models.CharField(blank=True, max_length=100)),
                ('voluntario_otra_org', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=10, null=True)),
                ('cual_org', models.CharField(blank=True, max_length=255)),
                ('hizo_hut', models.CharField(choices=[('SI', 'Sí'), ('TODAVIA_NO', 'Todavía no')], max_length=20)),
                ('hizo_hut_anio', models.CharField(blank=True, max_length=255, null=True)),
                ('hizo_reacciona', models.CharField(choices=[('SI', 'Sí'), ('TODAVIA_NO', 'Todavía no')], max_length=20)),
                ('cuando_reacciona', models.CharField(blank=True, max_length=255, null=True)),
                ('deseo_salir_campo', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('NO_POR_AHORA', 'No por ahora'), ('CORTO_PLAZO', 'Por corto plazo')], max_length=30, null=True)),
                ('nivel_estudio', models.CharField(blank=True, choices=[('PRIMARIA_COMPLETA', 'Primaria completa'), ('SECUNDARIA_INCOMPLETA', 'Secundaria incompleta'), ('SECUNDARIA_COMPLETA', 'Secundaria completa'), ('TERCIARIO_INCOMPLETO', 'Terciario incompleto'), ('TERCIARIO_COMPLETO', 'Terciario completo'), ('UNIVERSITARIO_INCOMPLETO', 'Universitario incompleto'), ('UNIVERSITARIO_COMPLETO', 'Universitario completo')], max_length=30, null=True)),
                ('titulo_universitario', models.CharField(blank=True, max_length=255, null=True)),
                ('cursos_formacion', models.TextField(blank=True)),
                ('experiencia_profesional', models.TextField(blank=True)),
                ('habla_idioma', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=10, null=True)),
                ('cual_idioma', models.CharField(blank=True, max_length=255, null=True)),
                ('lee_escribe_idioma', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=10, null=True)),
                ('cual_idioma_lee_escribe', models.CharField(blank=True, max_length=255, null=True)),
                ('otras_propuestas', models.TextField(blank=True, null=True)),
                ('foto_rostro', models.ImageField(blank=True, null=True, upload_to='fotos_rostro/', validators=[inscripciones.models.validar_extension_imagen])),
                ('areas_interes', models.ManyToManyField(blank=True, to='inscripciones.areainteres')),
            ],
            options={
                'verbose_name': 'Voluntario',
                'verbose_name_plural': 'Voluntarios',
            },
        ),
        migrations.CreateModel(
            name='ProvinciaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinciaNombre', models.CharField(max_length=100)),
                ('idPais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.pais')),
            ],
            options={
                'verbose_name': 'Provincia/Estado',
                'verbose_name_plural': 'Provincias/Estados',
            },
        ),
        migrations.CreateModel(
            name='GruposMoodle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Grupo')),
                ('horario', models.CharField(max_length=100, verbose_name='Horario')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=15, verbose_name='Día')),
                ('url_whatsapp', models.URLField(blank=True, null=True, verbose_name='URL WhatsApp')),
                ('capacidad', models.IntegerField(default=8, verbose_name='Capacidad')),
                ('participantes', models.IntegerField(default=0, verbose_name='Participantes')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscripciones.cursohut', verbose_name='Curso HUT')),
                ('tutores', models.ManyToManyField(blank=True, to='inscripciones.tutor', verbose_name='Tutores')),
            ],
            options={
                'verbose_name': 'Grupo Moodle',
                'verbose_name_plural': 'Grupos Moodle',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FormularioInscripcionHUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=25)),
                ('edad', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(13)])),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('congregacion', models.CharField(max_length=50)),
                ('pastor', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('estadoCivil', models.CharField(choices=[('Soltera/o', 'Soltera/o'), ('Casada/o', 'Casada/o')], max_length=9, verbose_name='Estado Civil')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('abandonado', models.BooleanField(default=False)),
                ('fecha_abandono', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('codigo_acceso', models.CharField(blank=True, help_text='Código único para que el alumno acceda a su panel', max_length=8, null=True, unique=True)),
                ('curso', models.ForeignKey(default=inscripciones.models.get_curso_activo, on_delete=django.db.models.deletion.CASCADE, to='inscripciones.cursohut', verbose_name='Curso HUT')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inscripciones.gruposmoodle', verbose_name='Grupo Moodle')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.pais')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.provinciaestado')),
            ],
            options={
                'verbose_name': 'Inscripción HUT',
                'verbose_name_plural': 'Inscripciones HUT',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
