# Generated by Django 4.2.28 on 2026-05-22 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruposmoodle',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inscripciones.pais', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='gruposmoodle',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inscripciones.provinciaestado', verbose_name='Provincia/Estado'),
        ),
    ]
