# Generated by Django 4.2.28 on 2026-02-28 19:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inscripciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_cursohut_formularioinscripcionhut_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioinscripcionhut',
            name='curso',
            field=models.ForeignKey(default=inscripciones.models.get_curso_activo, on_delete=django.db.models.deletion.CASCADE, to='inscripciones.cursohut', verbose_name='Curso HUT'),
        ),
        migrations.CreateModel(
            name='GruposMoodle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Grupo')),
                ('horario', models.CharField(max_length=100, verbose_name='Horario')),
                ('dia', models.CharField(max_length=100, verbose_name='Día')),
                ('tutor', models.CharField(max_length=100, verbose_name='Tutor')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscripciones.cursohut', verbose_name='Curso HUT')),
            ],
            options={
                'verbose_name': 'Grupo Moodle',
                'verbose_name_plural': 'Grupos Moodle',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='formularioinscripcionhut',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inscripciones.gruposmoodle', verbose_name='Grupo Moodle'),
        ),
    ]
