# Generated by Django 4.2.28 on 2026-05-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_gruposmoodle_pais_gruposmoodle_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinciaestado',
            name='gmt',
            field=models.CharField(blank=True, help_text='Ej: UTC-3', max_length=10, null=True),
        ),
    ]
