# Generated by Django 4.2.28 on 2026-03-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_alter_formularioinscripcionhut_curso_gruposmoodle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruposmoodle',
            name='capacidad',
            field=models.IntegerField(default=8, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='gruposmoodle',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gruposmoodle',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
