# Generated by Django 4.2.28 on 2026-05-22 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripciones', '0003_provinciaestado_gmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='areainteres',
            name='fecha_auditoria',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AddField(
            model_name='areainteres',
            name='usuario_auditoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='cursohut',
            name='fecha_auditoria',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AddField(
            model_name='cursohut',
            name='usuario_auditoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='formulariodedecision',
            name='fecha_auditoria',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AddField(
            model_name='formulariodedecision',
            name='usuario_auditoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='formularioinscripcionhut',
            name='fecha_auditoria',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AddField(
            model_name='formularioinscripcionhut',
            name='usuario_auditoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='gruposmoodle',
            name='fecha_auditoria',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AddField(
            model_name='gruposmoodle',
            name='usuario_auditoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='pais',
            name='fecha_auditoria',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AddField(
            model_name='pais',
            name='usuario_auditoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='provinciaestado',
            name='fecha_auditoria',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AddField(
            model_name='provinciaestado',
            name='usuario_auditoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='terminoscondiciones',
            name='fecha_auditoria',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AddField(
            model_name='terminoscondiciones',
            name='usuario_auditoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='fecha_auditoria',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='usuario_auditoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='fecha_auditoria',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='usuario_auditoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación'),
        ),
    ]
