# Generated by Django 4.2.28 on 2026-03-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_gruposmoodle_capacidad_gruposmoodle_fecha_baja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruposmoodle',
            name='participantes',
            field=models.IntegerField(default=0, verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='gruposmoodle',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=15, verbose_name='Día'),
        ),
    ]
