# Generated by Django 4.2.28 on 2026-05-22 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_areainteres_fecha_auditoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariodedecision',
            name='fecha_auditoria',
        ),
        migrations.RemoveField(
            model_name='formulariodedecision',
            name='usuario_auditoria',
        ),
        migrations.RemoveField(
            model_name='formularioinscripcionhut',
            name='fecha_auditoria',
        ),
        migrations.RemoveField(
            model_name='formularioinscripcionhut',
            name='usuario_auditoria',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='fecha_auditoria',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='usuario_auditoria',
        ),
    ]
