# Generated by Django 4.2.28 on 2026-06-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0005_remove_formulariodedecision_fecha_auditoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursohut',
            name='password_curso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contraseña Curso'),
        ),
    ]
