# Generated by Django 4.2.28 on 2026-03-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0006_set_codigo_acceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioinscripcionhut',
            name='codigo_acceso',
        ),
    ]
