# Generated by Django 4.2.28 on 2026-03-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0007_remove_formularioinscripcionhut_codigo_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioinscripcionhut',
            name='codigo_acceso',
            field=models.CharField(blank=True, help_text='Código único para que el alumno acceda a su panel', max_length=8, null=True, unique=True),
        ),
    ]
