# Generated by Django 4.2.28 on 2026-03-07 02:44

from django.db import migrations
import string
import random

def generate_codigo_unico(apps, schema_editor):
    FormularioInscripcionHUT = apps.get_model('inscripciones', 'FormularioInscripcionHUT')
    
    for inscripcion in FormularioInscripcionHUT.objects.all():
        if not inscripcion.codigo_acceso:
            while True:
                random_chars = ''.join(random.choices(string.ascii_uppercase + string.digits, k=5))
                codigo = f"HUT-{random_chars}"
                if not FormularioInscripcionHUT.objects.filter(codigo_acceso=codigo).exists():
                    inscripcion.codigo_acceso = codigo
                    inscripcion.save(update_fields=['codigo_acceso'])
                    break

class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0008_formularioinscripcionhut_codigo_acceso'),
    ]

    operations = [
        migrations.RunPython(generate_codigo_unico, migrations.RunPython.noop),
    ]
