# Generated by Django 4.2.28 on 2026-03-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0009_run_codigo_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruposmoodle',
            name='url_whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='URL WhatsApp'),
        ),
    ]
