# Generated by Django 4.2.28 on 2026-04-21 16:29

from django.db import migrations, models
import inscripciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0010_gruposmoodle_url_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='con_quien_convive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='cual_idioma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='cuando_reacciona',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='fechas_nacimiento_hijos',
            field=models.TextField(blank=True, help_text='Ej: Juan (12-05-2015)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='habla_idioma',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='hijos',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=10),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='hizo_hut_anio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='lee_escribe_idioma',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='nombre_pastor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='otras_propuestas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='rol_agencia',
            field=models.CharField(blank=True, choices=[('CANDIDATO', 'Candidato'), ('VOLUNTARIO', 'Voluntario'), ('INTERESADO', 'Interesado')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='telefono_pastor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='titulo_universitario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='areainteres',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='deseo_salir_campo',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('NO_POR_AHORA', 'No por ahora'), ('CORTO_PLAZO', 'Por corto plazo')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='foto_rostro',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_rostro/', validators=[inscripciones.models.validar_extension_imagen]),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='miembro_iglesia',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='nivel_estudio',
            field=models.CharField(blank=True, choices=[('PRIMARIA_COMPLETA', 'Primaria completa'), ('SECUNDARIA_INCOMPLETA', 'Secundaria incompleta'), ('SECUNDARIA_COMPLETA', 'Secundaria completa'), ('TERCIARIO_INCOMPLETO', 'Terciario incompleto'), ('TERCIARIO_COMPLETO', 'Terciario completo'), ('UNIVERSITARIO_INCOMPLETO', 'Universitario incompleto'), ('UNIVERSITARIO_COMPLETO', 'Universitario completo')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='pais_residencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='sirve_en_iglesia',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='voluntario_otra_org',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=10, null=True),
        ),
    ]
