# Generated by Django 4.2.28 on 2026-04-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0011_voluntario_con_quien_convive_voluntario_cual_idioma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='cual_idioma_lee_escribe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
