# Generated by Django 4.2.28 on 2026-04-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0012_voluntario_cual_idioma_lee_escribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminosCondiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CANDIDATO', 'Candidato'), ('VOLUNTARIO', 'Voluntario'), ('INTERESADO', 'Interesado')], max_length=30, unique=True)),
                ('texto_html', models.TextField(help_text='Texto HTML para los términos y condiciones de este rol.')),
            ],
            options={
                'verbose_name': 'Términos y Condiciones',
                'verbose_name_plural': 'Términos y Condiciones',
            },
        ),
    ]
