# Generated by Django 4.2.28 on 2026-04-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0013_terminoscondiciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursohut',
            name='inscripciones_abiertas',
            field=models.BooleanField(default=False, verbose_name='Inscripciones Abiertas'),
        ),
    ]
